# Generated by Django 2.2.6 on 2019-11-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('quote_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteapp.QuoteCategory')),
            ],
        ),
    ]
